/* liquid-glass.tsx — GENERATED by scripts/sync.mjs. Do not edit.
 *
 * Lifted from clarity-platform so the ten-layer material and the CSS in
 * @clarity-studio/design/glass.css can never disagree about the DOM shape.
 * Re-run: pnpm design:sync --source <path-to-clarity-platform>
 */

import * as React from 'react';

import { cn } from './ui.js';

/**
 * LiquidGlass — the real glass material.
 *
 * Faithful port of the tonnitools.com/liquid-glass recipe. Ten sibling layers,
 * each contributing its own `backdrop-filter` pass: edge reflection, emboss,
 * refraction, blur, two blend passes, a specular highlight, and inert
 * tint/contrast/brightness passes that only engage when you tune them.
 *
 * The structural CSS lives in `globals.css` under `.liquid-glass`; this
 * component owns the DOM shape and maps props onto the `--lg-*` variables.
 *
 * COST: ten backdrop-filter passes. Use it for a surface that *is* the screen —
 * a modal, the dock, a sheet, the one card the page is about. For ordinary
 * surfaces use the flat `.glass-card` / `.glass-button` / `.glass-input`
 * utilities, which land the same look in a single pass.
 *
 * LAYOUT: the container is `pointer-events: none` (the content sits in a
 * `pointer-events: auto` child) and the edge reflection bleeds ~16px outside
 * the box via a negative margin. Give it breathing room, and don't wrap it in
 * an `overflow: hidden` ancestor or the reflection gets clipped.
 *
 * @example
 * <LiquidGlass radius={28} className="w-80">
 *   <div className="p-6">…</div>
 * </LiquidGlass>
 */
export interface LiquidGlassProps extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Corner radius in px, all four corners. Default 24.
   *
   * This MUST match the `rounded-*` on `contentClassName` — the material and
   * the content box are separate elements, so a mismatch shows as fill reaching
   * a corner the blur doesn't. Note this project overrides Tailwind's scale:
   * `rounded-lg` 8 · `rounded-xl` 16 · `rounded-2xl` 24 · `rounded-3xl` 32.
   * `glass-recipe.test.ts` enforces the pairing.
   */
  radius?: number;
  /**
   * Per-corner radii in px, overriding `radius` for the corners you name.
   * The material follows the content box exactly, so a bottom sheet must set
   * these rather than only rounding the content — otherwise the fill reaches
   * the square corner and the blur behind it does not.
   *
   * @example {{ br: 0, bl: 0 }}  // sheet: rounded top, flush bottom
   */
  radii?: { tl?: number; tr?: number; br?: number; bl?: number };
  /** Base blur strength in px — the "Strength" control. Default 14. */
  strength?: number;
  /** Edge softness in px, drives the emboss/refraction band widths. Default 12. */
  softness?: number;
  /** Additional blur in px on top of `strength`. Default 2. */
  extraBlur?: number;
  /** Full-surface invert, 0–1. Default 0.1. */
  invert?: number;
  /** Specular strength of the edge highlight, 0–1. Default 1. */
  edgeSpecularity?: number;
  /** Tint amount, 0–1. At 0 the tint layer is a no-op. Default 0. */
  tint?: number;
  /** Tint hue rotation in degrees, applied in proportion to `tint`. Default 180. */
  tintHue?: number;
  /** Tint saturation multiplier, applied in proportion to `tint`. Default 2. */
  tintSaturation?: number;
  /** Backdrop contrast multiplier. 1 is a no-op. Default 1. */
  contrast?: number;
  /** Backdrop brightness multiplier. 1 is a no-op. Default 1. */
  brightness?: number;
  /** Flat color washed over the stack, e.g. `rgba(255,255,255,0.06)`. */
  background?: string;
  /** Classes for the inner content box (padding, layout, text color). */
  contentClassName?: string;
  children?: React.ReactNode;
}

/** The ten material layers, in paint order. Class names match globals.css. */
const MATERIAL_LAYERS = [
  'lg-edge-reflection',
  'lg-emboss-reflection',
  'lg-refraction',
  'lg-blur',
  'lg-blend-layers',
  'lg-blend-edge',
  'lg-highlight',
  'lg-tint',
  'lg-contrast',
  'lg-brightness',
] as const;

export const LiquidGlass = React.forwardRef<HTMLDivElement, LiquidGlassProps>(
  function LiquidGlass(
    {
      radius,
      radii,
      strength,
      softness,
      extraBlur,
      invert,
      edgeSpecularity,
      tint,
      tintHue,
      tintSaturation,
      contrast,
      brightness,
      background,
      className,
      contentClassName,
      children,
      style,
      ...props
    },
    ref
  ) {
    // Only emit the variables the caller actually set — everything else falls
    // through to the tonnitools defaults declared on `.liquid-glass`.
    const vars: React.CSSProperties = { ...style };
    const set = (name: string, value: string | undefined) => {
      if (value !== undefined) {
        (vars as Record<string, string>)[name] = value;
      }
    };

    set('--lg-corner-radius', radius === undefined ? undefined : `${radius}px`);
    set('--lg-radius-tl', radii?.tl === undefined ? undefined : `${radii.tl}px`);
    set('--lg-radius-tr', radii?.tr === undefined ? undefined : `${radii.tr}px`);
    set('--lg-radius-br', radii?.br === undefined ? undefined : `${radii.br}px`);
    set('--lg-radius-bl', radii?.bl === undefined ? undefined : `${radii.bl}px`);
    set('--lg-base-strength', strength === undefined ? undefined : `${strength}px`);
    set('--lg-softness', softness === undefined ? undefined : `${softness}px`);
    set('--lg-extra-blur', extraBlur === undefined ? undefined : `${extraBlur}px`);
    set('--lg-invert', invert === undefined ? undefined : `${invert * 100}%`);
    set('--lg-edge-specularity', edgeSpecularity?.toString());
    set('--lg-tint-amount', tint?.toString());
    set('--lg-tint-hue', tintHue === undefined ? undefined : `${tintHue}deg`);
    set('--lg-tint-saturation', tintSaturation?.toString());
    set('--lg-contrast', contrast?.toString());
    set('--lg-brightness', brightness?.toString());
    set('--lg-background', background);

    return (
      <div ref={ref} className={cn('liquid-glass', className)} style={vars} {...props}>
        <div className={cn('liquid-glass__content', contentClassName)}>{children}</div>
        <div className="liquid-glass__material" aria-hidden="true">
          {MATERIAL_LAYERS.map((layer) => (
            <div key={layer} className={layer} />
          ))}
        </div>
      </div>
    );
  }
);
