/**
 * Compose override generation.
 *
 * Studio does not own the automation's `docker-compose.yml` — the automation
 * does, and it must keep working when someone runs `docker compose up` without
 * Studio installed. So instead of generating a compose file, Studio generates
 * an *override* and layers it on:
 *
 *   docker compose -p studio-<id> -f docker-compose.yml -f .studio/compose.override.yml up
 *
 * The override owns only what is genuinely Studio's business: where the control
 * plane lives, which host port to publish, and how much of the machine this
 * automation is allowed to eat. Everything else — sidecars, extra services,
 * volumes the author added — passes through untouched.
 */

export interface OverrideOptions {
  /** Service in the automation's compose file to attach to. */
  service?: string;
  /** Host port to publish the automation's 3200 on. */
  hostPort: number;
  /** Environment from ControlPlane.environmentFor(). */
  environment: Record<string, string>;
  projectId: string;
  /** Memory limit, e.g. "1g". A runaway agent loop shouldn't take the laptop
   *  down with it. */
  memory?: string;
  cpus?: number;
  /** Cut the container off from everything except the control plane and the
   *  hosts its declared integrations actually need. */
  strictEgress?: boolean;
}

const CONTAINER_PORT = 3200;

export function buildComposeOverride(opts: OverrideOptions): string {
  const service = opts.service ?? 'automation';
  const env = Object.entries(opts.environment)
    .map(([k, v]) => `      ${k}: ${quote(v)}`)
    .join('\n');

  const lines = [
    '# Generated by Clarity Studio. Do not edit — regenerated on every start.',
    '#',
    '# This file layers Studio-specific settings over the automation\'s own',
    '# docker-compose.yml. The automation still runs standalone without it.',
    'services:',
    `  ${service}:`,
    '    ports:',
    `      - "127.0.0.1:${opts.hostPort}:${CONTAINER_PORT}"`,
    '    environment:',
    env,
    // Docker restarts a crashed container behind Studio's back, which turns a
    // boot failure into an invisible loop. Studio owns restart decisions so it
    // can surface the crash instead.
    '    restart: "no"',
    // Linux has no host.docker.internal unless you add it; macOS and Windows
    // do. Adding it unconditionally is harmless on the latter.
    '    extra_hosts:',
    '      - "host.docker.internal:host-gateway"',
    '    labels:',
    `      ai.clarity.studio.project: ${quote(opts.projectId)}`,
    '      ai.clarity.studio.managed: "true"',
  ];

  if (opts.memory) lines.push(`    mem_limit: ${opts.memory}`);
  if (opts.cpus) lines.push(`    cpus: ${opts.cpus}`);
  lines.push('    pids_limit: 512');

  if (opts.strictEgress) {
    lines.push(
      '    networks:',
      '      - studio-internal',
      'networks:',
      '  studio-internal:',
      '    internal: true',
    );
  }

  return lines.join('\n') + '\n';
}

/**
 * Quote a YAML scalar only when it needs it, so the generated file stays
 * readable — someone will eventually have to debug it by eye.
 *
 * The cases that must be quoted are the ones YAML would silently retype:
 * `false` becomes a boolean and `3200` becomes an integer, and Compose rejects
 * a non-string environment value. `ENABLE_DEBUG: false` failing at
 * `docker compose up` with a schema error is a miserable thing to debug.
 */
const YAML_AMBIGUOUS = /^(?:true|false|yes|no|on|off|null|~)$/i;

function quote(value: string): string {
  if (value === '') return '""';
  if (YAML_AMBIGUOUS.test(value)) return JSON.stringify(value);
  if (/^[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?$/.test(value)) return JSON.stringify(value);
  if (/^[A-Za-z0-9_./:@-]+$/.test(value)) return value;
  return JSON.stringify(value);
}

export function composeArgs(opts: {
  projectId: string;
  composeFile: string;
  overrideFile: string;
}): string[] {
  return [
    'compose',
    '-p',
    `studio-${opts.projectId}`,
    '-f',
    opts.composeFile,
    '-f',
    opts.overrideFile,
  ];
}
