#!/usr/bin/env node
/**
 * Pull the design system out of the Claritty platform.
 *
 * Two different jobs, handled two different ways on purpose:
 *
 * 1. **Generated.** The CSS custom properties and the `glass-*` recipes are
 *    lifted verbatim out of `globals.css`. They are pure CSS with no app
 *    coupling, so copying them mechanically is safe and re-runnable.
 *
 * 2. **Asserted.** The Tailwind preset is hand-written, because parsing a
 *    TypeScript config that imports plugins is a fragile way to get a value
 *    you could just read. But a hand-written file drifts silently, so this
 *    script *checks* the load-bearing constants against upstream and fails if
 *    they have moved. `md: 920px` is the one that matters most: it is not
 *    Tailwind's default, and getting it wrong breaks every responsive layout
 *    in a way that looks like a styling mistake rather than a config one.
 *
 * Usage:
 *   node scripts/sync.mjs --source <path-to-clarity-platform> [--check]
 *
 * `--check` writes nothing and exits non-zero on any difference. That is what
 * CI runs.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, '..', 'src');

const args = process.argv.slice(2);
const check = args.includes('--check');
const sourceArg = args[args.indexOf('--source') + 1];
const SOURCE =
  args.includes('--source') && sourceArg
    ? resolve(sourceArg)
    : resolve(HERE, '../../../vendor/clarity-platform');

/** Constants the hand-written preset depends on. If upstream moves one of
 *  these, the preset is wrong and CI should say so. */
const ASSERTIONS = [
  {
    file: 'tailwind.config.ts',
    what: 'the md breakpoint',
    // Keys may be quoted or bare depending on how the file has been formatted.
    pattern: /['"]?md['"]?\s*:\s*['"]920px['"]/,
    why: "Studio's preset hard-codes md: 920px. Tailwind's default is 768px.",
  },
  {
    file: 'src/app/globals.css',
    what: 'the accent colour',
    pattern: /--accent:\s*227\s+100%\s+68%/,  // an HSL triplet, not a hex
    why: 'The accent (#5B7FFF) is the one brand colour the whole UI leans on.',
  },
  {
    file: 'tailwind.config.ts',
    what: 'hoverOnlyWhenSupported',
    pattern: /['"]?hoverOnlyWhenSupported['"]?\s*:\s*true/,
    why: 'Without it, hover styles stick after a tap on touch devices.',
  },
];

function read(relative) {
  const path = join(SOURCE, relative);
  if (!existsSync(path)) {
    console.error(
      `\nCannot find ${relative} under ${SOURCE}.\n` +
        `  Point at a clarity-platform checkout:\n` +
        `    node scripts/sync.mjs --source ../clarity-platform\n`,
    );
    process.exit(2);
  }
  return readFileSync(path, 'utf8');
}

/** Everything between `selector {` and its matching close brace. */
function block(css, selector) {
  const start = css.indexOf(`${selector} {`);
  if (start === -1) return undefined;
  let depth = 0;
  for (let i = css.indexOf('{', start); i < css.length; i++) {
    if (css[i] === '{') depth++;
    else if (css[i] === '}') {
      depth--;
      if (depth === 0) return css.slice(start, i + 1);
    }
  }
  return undefined;
}

/** Every `.glass-*` rule, in source order. */
function glassRules(css) {
  const out = [];
  const re = /^\s*(\.[a-zA-Z0-9_-]*glass[a-zA-Z0-9_-]*(?:\s*,\s*\.[a-zA-Z0-9_-]+)*)\s*\{/gm;
  let match;
  while ((match = re.exec(css)) !== null) {
    const rule = block(css, match[1].trim());
    if (rule) out.push(rule.trim());
  }
  return out;
}

const globals = read('src/app/globals.css');
const config = read('tailwind.config.ts');

// ── assertions ───────────────────────────────────────────────────────────────
const drifted = ASSERTIONS.filter((a) => !a.pattern.test(a.file.endsWith('.css') ? globals : config));
if (drifted.length > 0) {
  console.error('\nUpstream design values have moved:\n');
  for (const d of drifted) console.error(`  ✘ ${d.what} (${d.file})\n    ${d.why}`);
  console.error('\nUpdate src/tailwind-preset.ts to match, then re-run.\n');
  process.exit(1);
}

// ── tokens.css ───────────────────────────────────────────────────────────────
const root = block(globals, ':root');
const dark = block(globals, '.dark');
if (!root || !dark) {
  console.error('Could not find the :root / .dark token blocks in globals.css.');
  process.exit(2);
}

const header = (name) => `/* ${name} — GENERATED by scripts/sync.mjs. Do not edit.
 *
 * Lifted from clarity-platform so Studio and the platform cannot drift apart.
 * Re-run: pnpm design:sync --source <path-to-clarity-platform>
 */\n\n`;

const tokensCss = header('tokens.css') + `${root}\n\n${dark}\n`;

// ── glass.css ────────────────────────────────────────────────────────────────
const rules = glassRules(globals);
if (rules.length === 0) {
  console.error('Found no .glass-* rules in globals.css — has the recipe been renamed?');
  process.exit(2);
}
const glassCss =
  header('glass.css') +
  '/* The house surface. Floating panels use these; flat opaque fills are the\n' +
  ' * anti-pattern they exist to prevent. */\n\n' +
  rules.join('\n\n') +
  '\n';

// ── write or check ───────────────────────────────────────────────────────────
const outputs = [
  ['tokens.css', tokensCss],
  ['glass.css', glassCss],
];

let changed = 0;
for (const [name, content] of outputs) {
  const path = join(OUT, name);
  const current = existsSync(path) ? readFileSync(path, 'utf8') : '';
  if (current === content) {
    console.log(`  = ${name} (unchanged)`);
    continue;
  }
  changed++;
  if (check) {
    console.error(`  ✘ ${name} is out of date`);
  } else {
    writeFileSync(path, content, 'utf8');
    console.log(`  ✓ ${name} (${content.split('\n').length} lines)`);
  }
}

if (check && changed > 0) {
  console.error('\nRun `pnpm design:sync` and commit the result.\n');
  process.exit(1);
}

console.log(`\n${rules.length} glass rule(s), ${ASSERTIONS.length} assertion(s) verified.\n`);
