/**
 * Mark the seed's integration catalog with what Studio can actually broker.
 *
 * The catalog describes the HOSTED platform's integrations — 38 services, each
 * manifest naming real tool ids. Studio brokers a subset, from
 * `packages/connectors`. A coding agent working inside an automation reads those
 * manifests, sees `jira.create_issue`, and builds with it. Studio cannot call it.
 *
 * That is not the agent being careless; it is the catalog being ambiguous. Its
 * own skill says "never invent a tool id" — and the agent did not invent one, it
 * read one. The gap between "the platform provides this" and "this machine can
 * call it" was nowhere in the folder.
 *
 * So every manifest gets `localConnector`, and every tool in it gets `local`.
 * Nothing is deleted: a service Studio cannot broker yet is still worth knowing
 * about, and the add-an-integration skill turns that into a connector request.
 *
 * Regenerate with `pnpm sync:catalog`; CI asserts the tree is unchanged, so the
 * annotations cannot drift away from the connectors they describe.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CATALOG_DIR = join(ROOT, 'packages/automation-seed/catalog/integrations');
const { CATALOG } = await import(join(ROOT, 'packages/connectors/dist/index.js'));

const localById = new Map(CATALOG.map((c) => [c.id, c]));
const localToolIds = new Set(CATALOG.flatMap((c) => c.tools.map((t) => t.id)));

// A connector with no manifest is undiscoverable: an agent reads the catalog to
// learn what exists, so Telegram-but-not-WhatsApp means half the reach-you
// options are invisible. Write the missing ones from the connector itself.
for (const connector of CATALOG) {
  const file = join(CATALOG_DIR, connector.id, 'manifest.json');
  if (existsSync(file)) continue;
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(
    file,
    `${JSON.stringify(
      {
        id: connector.id,
        kind: 'integration',
        transport: 'native',
        version: '1.0.0',
        name: connector.name,
        description: connector.tools[0]?.summary ?? '',
        // The connector's own sentence — where the credential comes from, in
        // the words Studio shows the person connecting it.
        setupGuide: connector.howToConnect,
        authType: connector.tools[0]?.auth?.type ?? 'none',
        providedTools: connector.tools.map((t) => ({ id: t.id, description: t.summary ?? '' })),
      },
      null,
      2,
    )}\n`,
  );
}

const rows = [];

for (const dir of readdirSync(CATALOG_DIR).sort()) {
  const file = join(CATALOG_DIR, dir, 'manifest.json');
  if (!existsSync(file)) continue;

  const manifest = JSON.parse(readFileSync(file, 'utf8'));
  const connector = localById.get(manifest.id);

  manifest.localConnector = Boolean(connector);
  manifest._localNote = connector
    ? 'Studio can broker this. Only tools marked "local": true can be called — the rest are hosted-platform only.'
    : 'Studio CANNOT broker this yet: no connector in packages/connectors. Calling any of these tools from an ' +
      'automation will fail at run time. See .claude/skills/add-an-integration/SKILL.md to request one.';

  const provided = manifest.providedTools ?? [];
  for (const tool of provided) {
    tool.local = localToolIds.has(tool.id);
  }

  // Tools the connector implements that the catalog never mentioned — an agent
  // reading only the manifest would never find them.
  if (connector) {
    const named = new Set(provided.map((t) => t.id));
    for (const tool of connector.tools) {
      if (!named.has(tool.id)) {
        provided.push({ id: tool.id, description: tool.summary ?? '', local: true });
      }
    }
    manifest.providedTools = provided;
  }

  writeFileSync(file, `${JSON.stringify(manifest, null, 2)}\n`);

  rows.push({
    id: manifest.id,
    name: manifest.name ?? manifest.id,
    local: Boolean(connector),
    tools: provided.filter((t) => t.local).map((t) => t.id),
    fields: connector?.fields.map((f) => f.key) ?? [],
    // Carried for the docs: a service Studio cannot broker yet is still worth
    // describing, and every one of these tool ids is real on the platform.
    category: manifest.category ?? 'other',
    description: manifest.description ?? '',
    authType: manifest.authType ?? 'none',
    allTools: provided.map((t) => t.id),
  });
}

const available = rows.filter((r) => r.local).sort((a, b) => a.id.localeCompare(b.id));
const missing = rows.filter((r) => !r.local).sort((a, b) => a.id.localeCompare(b.id));

writeFileSync(
  join(ROOT, 'packages/automation-seed/catalog/AVAILABLE.md'),
  `<!-- Generated by \`pnpm sync:catalog\`. Do not edit by hand. -->

# What this machine can actually call

Studio brokers integrations locally, with your own credentials, from its
connector catalog. The manifests in \`integrations/\` describe the hosted
platform's full set — **which is larger than this**. A tool that is not listed
below cannot be called from an automation running here: the call fails at run
time, no matter how sensible the id looks.

If you need something that is not here, do not reach for the closest-looking id.
Read \`.claude/skills/add-an-integration/SKILL.md\` and write the connector
request — that is a defined path, and it takes an afternoon.

## Available (${available.length})

| Integration | Tools you can call | Credentials it asks for |
| --- | --- | --- |
${available
  .map((r) => `| **${r.name}** (\`${r.id}\`) | ${r.tools.map((t) => `\`${t}\``).join('<br>') || '—'} | ${r.fields.map((f) => `\`${f}\``).join(', ') || '—'} |`)
  .join('\n')}

## Not available here yet (${missing.length})

The platform provides these; Studio has no connector for them. Their manifests
are still in \`integrations/\` because knowing the service exists is useful — but
every tool they name will fail if you call it.

${missing.map((r) => `\`${r.id}\``).join(' · ')}
`,
);

// ── the setup reference a new user actually needs ────────────────────────────
//
// The wall in front of anyone installing this is not the install; it is thirteen
// services each wanting a different credential from a different dashboard. That
// page has to be exhaustive and it has to be current, which rules out writing it
// by hand — a connector added next month would silently not appear.
//
// So it is generated from the same specs the app uses, including the very
// sentence Studio shows in the Connect form. Docs and product cannot disagree
// because there is one source.
// The engine's auth kinds, read out of its own type rather than remembered. A
// seventh kind added to the union without a sentence here fails this script,
// which is the point: the docs cannot quietly describe six of seven.
const AUTH_SENTENCES = {
  bearer: 'an `Authorization: Bearer <field>` header. Most APIs.',
  header: 'a named header, with an optional prefix.',
  query: 'a query parameter.',
  basic: 'base64 `user:pass`, built from two fields.',
  oauth2:
    "a refresh token exchanged for an access token against the provider's own token endpoint, using **your own** app. There is no Claritty client id to fall back on.",
  none: 'a public API, no credential.',
};

const authUnion = /type:\s*((?:'[a-z0-9]+'\s*\|\s*)+'[a-z0-9]+')\s*;/i.exec(
  readFileSync(join(ROOT, 'packages/connectors/src/engine.ts'), 'utf8'),
);
if (!authUnion) throw new Error('could not read the auth-type union out of packages/connectors/src/engine.ts');
const authKinds = [...authUnion[1].matchAll(/'([a-z0-9]+)'/gi)].map((m) => m[1]);
for (const kind of authKinds) {
  if (!AUTH_SENTENCES[kind]) {
    throw new Error(`auth kind "${kind}" has no sentence in sync-catalog.mjs — write one, then regenerate.`);
  }
}

// A worked example, taken from a connector that actually ships rather than
// written for the docs. Keys unquoted so it is the TypeScript you would paste.
const example = localById.get('slack') ?? CATALOG[0];
const exampleSpec = JSON.stringify(
  {
    id: example.id,
    name: example.name,
    howToConnect: example.howToConnect,
    fields: example.fields,
    tools: example.tools.slice(0, 1),
  },
  null,
  2,
).replace(/^(\s*)"([A-Za-z_][A-Za-z0-9_]*)":/gm, '$1$2:');

// Category ids read as headings. Only the ones a capitalize() gets wrong.
const CATEGORY_LABELS = { ai: 'AI', crm: 'CRM', dev: 'Developer tools' };
const categoryLabel = (id) => CATEGORY_LABELS[id] ?? `${id[0].toUpperCase()}${id.slice(1)}`;

// Hosted-only services, grouped so 27 rows can be scanned rather than read.
const byCategory = new Map();
for (const row of missing) {
  if (!byCategory.has(row.category)) byCategory.set(row.category, []);
  byCategory.get(row.category).push(row);
}

const connectorDoc = [
  '<!-- Generated by `pnpm sync:catalog`. Do not edit by hand. -->',
  // Machine-readable, for anything that renders this file and wants the counts
  // without parsing prose. claritty.ai reads exactly this line.
  `<!-- catalog: available=${available.length} missing=${missing.length} -->`,
  '',
  '# Connecting a service',
  '',
  'Everything here is stored in your operating system keyring — Keychain on macOS,',
  'DPAPI on Windows, libsecret on Linux — and brokered by Studio, so an automation',
  'never holds a credential. Connect once in **Settings → Connections** and every',
  'automation on the machine can use it.',
  '',
  '**Nothing here is a Claritty account.** Where a service needs an OAuth app —',
  'Gmail, Jira, WhatsApp — you create your own. There is no Claritty client id to',
  'sign into, which is the point: your automations talk to your accounts.',
  '',
  `## The ${available.length} you can connect`,
  '',
  ...available.flatMap((r) => {
    const spec = localById.get(r.id);
    return [
      `### ${r.name}`,
      '',
      spec?.howToConnect ?? '',
      '',
      '| Field | | |',
      '| --- | --- | --- |',
      ...(spec?.fields ?? []).map(
        (f) => `| \`${f.key}\` | ${f.label} | ${f.secret ? 'secret' : 'not secret'}${f.placeholder ? ` · e.g. \`${f.placeholder}\`` : ''} |`,
      ),
      '',
      `Tools an automation can call: ${r.tools.map((t) => `\`${t}\``).join(', ')}`,
      '',
    ];
  }),
  `## The other ${missing.length}, which Studio cannot broker yet`,
  '',
  'The hosted platform provides these. Studio has no connector for them, so an',
  'automation that calls one **fails at run time**, however sensible the id looks.',
  '',
  'They are listed in full rather than hidden, for two reasons. Every tool id below',
  'is real, so knowing the exact name is most of the work of adding it. And a name',
  'you can see is a name nobody has to guess: the expensive failure here is an agent',
  'inventing `jira.create_issue` because the shape of the id was obvious.',
  '',
  ...[...byCategory.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .flatMap(([category, items]) => [
      `### ${categoryLabel(category)}`,
      '',
      '| Service | What it does | Tools it names | Credential |',
      '| --- | --- | --- | --- |',
      ...items.map(
        (r) =>
          `| **${r.name}** (\`${r.id}\`) | ${r.description} | ${r.allTools.map((t) => `\`${t}\``).join(' ') || '—'} | ${r.authType} |`,
      ),
      '',
    ]),
  `## Adding a connector for one of the ${missing.length}`,
  '',
  'This is a defined job rather than a wish, and it takes an afternoon. A connector',
  'is declarative: no code runs per service, so what you are writing is a spec the',
  'engine executes.',
  '',
  '### 1. Write the request',
  '',
  'From inside an automation, ask your coding agent for the `add-an-integration`',
  'skill. It produces `INTEGRATION-REQUEST.md`: where a person gets the credential,',
  'the fields, the auth type, and one block per operation you actually need. A',
  'connector with three used tools beats one with thirty untested ones.',
  '',
  'Do this rather than reaching for the closest-looking tool id. A manifest naming a',
  'tool nothing implements passes validation, runs, gets skipped, and reports',
  'success, which is the worst way for an automation to fail.',
  '',
  '### 2. Pick the auth type',
  '',
  "One of the engine's, and which field carries it:",
  '',
  '| Type | Is |',
  '| --- | --- |',
  ...authKinds.map((kind) => `| \`${kind}\` | ${AUTH_SENTENCES[kind]} |`),
  '',
  'If the provider only accepts a value in the URL, as Telegram does with the bot',
  'token and WhatsApp with the phone number id, name those fields in',
  "`pathCredentials` on the tool. That is opt-in on purpose, and every named value",
  'is scrubbed out of anything the call throws.',
  '',
  '### 3. Add the spec',
  '',
  `It goes in \`packages/connectors/src/catalog.ts\`. This is ${example.name}, whole:`,
  '',
  '```ts',
  exampleSpec,
  '```',
  '',
  '`{arg.x}` is an argument from the automation. A body value that is *exactly*',
  '`{arg.x}` keeps its type; `"{arg.x} items"` makes it a string. `result` is a',
  'dotted path into the response, or omit it to return the whole body.',
  '',
  '### 4. The rules the engine enforces',
  '',
  '- **A credential may not appear in a URL** unless the spec names it in',
  '  `pathCredentials`. `{creds.*}` in a url or query is rejected outright, because',
  '  those leak into logs, error messages and run history. Use `auth`.',
  '- **Public hosts only.** No localhost, link-local or private ranges. An',
  "  automation that takes a URL as input must not become a way to reach your",
  '  router or a cloud metadata endpoint.',
  '',
  '### 5. Prove it, then regenerate',
  '',
  '```bash',
  'pnpm test                 # the engine, including your spec',
  'pnpm proof:integrations   # a real HTTP call through the vault, credential never leaving the host',
  'pnpm sync:catalog         # this page, the seed catalog and llms.txt',
  '```',
  '',
  'That last command is what moves the service out of the table above and into the',
  'list at the top, everywhere it is named, including on claritty.ai. Nothing about',
  'a connector is written by hand twice.',
  '',
].join('\n');

mkdirSync(join(ROOT, 'docs'), { recursive: true });
writeFileSync(join(ROOT, 'docs/connectors.md'), `${connectorDoc}\n`);

// An index for the agents that read this repo. Postiz publishes one; here it is
// less of a nicety, because the people using Studio point Claude Code and Codex
// at these files daily. An agent that finds connectors.md does not invent a tool
// id — which is the failure that has cost the most here.
writeFileSync(
  join(ROOT, 'docs/llms.txt'),
  [
    '# Clarity Studio',
    '',
    '> Open-source desktop app for agentic automations. Runs on your machine with',
    '> your own keys: no account, no telemetry. Automations are declared in',
    '> `intelligence.yaml` and executed by the published `claritty-sdk` from PyPI.',
    '',
    '## Docs',
    '',
    '- [README](README.md): what it is, and getting started in three stages — run one with no credentials, add a model, connect a service.',
    `- [Connecting a service](docs/connectors.md): all ${available.length} connectors, their exact setup steps, credential fields and callable tool ids; the ${missing.length} the platform provides that Studio cannot broker yet, with the tool ids they name; and how to add one. GENERATED — the authority on what a tool id is.`,
    '- [Custom model endpoint](docs/model-endpoint.md): the exact request Studio sends to an OpenAI-compatible server, and what a response must contain for an agent loop to complete.',
    '- [Contributing](CONTRIBUTING.md): how to get green, and the four things that catch people out.',
    '',
    '## For an agent writing an automation',
    '',
    'Inside an automation folder, read `CLAUDE.md` and `catalog/AVAILABLE.md` first.',
    'AVAILABLE.md is the only list of what the machine can actually call: a tool',
    'marked `"local": false` names something real that Studio cannot broker, and',
    'calling it fails at run time however sensible the id looks.',
    '',
    '## Notes',
    '',
    `- Connectable now: ${available.map((r) => r.id).join(', ')}.`,
    '- Schedules fire only while the app is open. Webhooks are served by the CLI, not the desktop app.',
    '- There is no Claritty OAuth client. Where a service needs an app — Gmail, Jira, WhatsApp — the user creates their own.',
    '',
  ].join('\n'),
);

console.log(`catalog annotated — ${available.length} brokerable, ${missing.length} not`);
console.log(`available: ${available.map((r) => r.id).join(', ')}`);
