/**
 * Mark the seed's integration catalog with what Studio can actually broker.
 *
 * The catalog describes the HOSTED platform's integrations — 38 services, each
 * manifest naming real tool ids. Studio brokers a subset, from
 * `packages/connectors`. A coding agent working inside an automation reads those
 * manifests, sees `jira.create_issue`, and builds with it. Studio cannot call it.
 *
 * That is not the agent being careless; it is the catalog being ambiguous. Its
 * own skill says "never invent a tool id" — and the agent did not invent one, it
 * read one. The gap between "the platform provides this" and "this machine can
 * call it" was nowhere in the folder.
 *
 * So every manifest gets `localConnector`, and every tool in it gets `local`.
 * Nothing is deleted: a service Studio cannot broker yet is still worth knowing
 * about, and the add-an-integration skill turns that into a connector request.
 *
 * Regenerate with `pnpm sync:catalog`; CI asserts the tree is unchanged, so the
 * annotations cannot drift away from the connectors they describe.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CATALOG_DIR = join(ROOT, 'packages/automation-seed/catalog/integrations');
const { CATALOG } = await import(join(ROOT, 'packages/connectors/dist/index.js'));

const localById = new Map(CATALOG.map((c) => [c.id, c]));
const localToolIds = new Set(CATALOG.flatMap((c) => c.tools.map((t) => t.id)));

// A connector with no manifest is undiscoverable: an agent reads the catalog to
// learn what exists, so Telegram-but-not-WhatsApp means half the reach-you
// options are invisible. Write the missing ones from the connector itself.
for (const connector of CATALOG) {
  const file = join(CATALOG_DIR, connector.id, 'manifest.json');
  if (existsSync(file)) continue;
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(
    file,
    `${JSON.stringify(
      {
        id: connector.id,
        kind: 'integration',
        transport: 'native',
        version: '1.0.0',
        name: connector.name,
        description: connector.tools[0]?.summary ?? '',
        // The connector's own sentence — where the credential comes from, in
        // the words Studio shows the person connecting it.
        setupGuide: connector.howToConnect,
        authType: connector.tools[0]?.auth?.type ?? 'none',
        providedTools: connector.tools.map((t) => ({ id: t.id, description: t.summary ?? '' })),
      },
      null,
      2,
    )}\n`,
  );
}

const rows = [];

for (const dir of readdirSync(CATALOG_DIR).sort()) {
  const file = join(CATALOG_DIR, dir, 'manifest.json');
  if (!existsSync(file)) continue;

  const manifest = JSON.parse(readFileSync(file, 'utf8'));
  const connector = localById.get(manifest.id);

  manifest.localConnector = Boolean(connector);
  manifest._localNote = connector
    ? 'Studio can broker this. Only tools marked "local": true can be called — the rest are hosted-platform only.'
    : 'Studio CANNOT broker this yet: no connector in packages/connectors. Calling any of these tools from an ' +
      'automation will fail at run time. See .claude/skills/add-an-integration/SKILL.md to request one.';

  const provided = manifest.providedTools ?? [];
  for (const tool of provided) {
    tool.local = localToolIds.has(tool.id);
  }

  // Tools the connector implements that the catalog never mentioned — an agent
  // reading only the manifest would never find them.
  if (connector) {
    const named = new Set(provided.map((t) => t.id));
    for (const tool of connector.tools) {
      if (!named.has(tool.id)) {
        provided.push({ id: tool.id, description: tool.summary ?? '', local: true });
      }
    }
    manifest.providedTools = provided;
  }

  writeFileSync(file, `${JSON.stringify(manifest, null, 2)}\n`);

  rows.push({
    id: manifest.id,
    name: manifest.name ?? manifest.id,
    local: Boolean(connector),
    tools: provided.filter((t) => t.local).map((t) => t.id),
    fields: connector?.fields.map((f) => f.key) ?? [],
  });
}

const available = rows.filter((r) => r.local).sort((a, b) => a.id.localeCompare(b.id));
const missing = rows.filter((r) => !r.local).sort((a, b) => a.id.localeCompare(b.id));

writeFileSync(
  join(ROOT, 'packages/automation-seed/catalog/AVAILABLE.md'),
  `<!-- Generated by \`pnpm sync:catalog\`. Do not edit by hand. -->

# What this machine can actually call

Studio brokers integrations locally, with your own credentials, from its
connector catalog. The manifests in \`integrations/\` describe the hosted
platform's full set — **which is larger than this**. A tool that is not listed
below cannot be called from an automation running here: the call fails at run
time, no matter how sensible the id looks.

If you need something that is not here, do not reach for the closest-looking id.
Read \`.claude/skills/add-an-integration/SKILL.md\` and write the connector
request — that is a defined path, and it takes an afternoon.

## Available (${available.length})

| Integration | Tools you can call | Credentials it asks for |
| --- | --- | --- |
${available
  .map((r) => `| **${r.name}** (\`${r.id}\`) | ${r.tools.map((t) => `\`${t}\``).join('<br>') || '—'} | ${r.fields.map((f) => `\`${f}\``).join(', ') || '—'} |`)
  .join('\n')}

## Not available here yet (${missing.length})

The platform provides these; Studio has no connector for them. Their manifests
are still in \`integrations/\` because knowing the service exists is useful — but
every tool they name will fail if you call it.

${missing.map((r) => `\`${r.id}\``).join(' · ')}
`,
);

// ── the setup reference a new user actually needs ────────────────────────────
//
// The wall in front of anyone installing this is not the install; it is thirteen
// services each wanting a different credential from a different dashboard. That
// page has to be exhaustive and it has to be current, which rules out writing it
// by hand — a connector added next month would silently not appear.
//
// So it is generated from the same specs the app uses, including the very
// sentence Studio shows in the Connect form. Docs and product cannot disagree
// because there is one source.
const connectorDoc = [
  '<!-- Generated by `pnpm sync:catalog`. Do not edit by hand. -->',
  '',
  '# Connecting a service',
  '',
  'Everything here is stored in your operating system keyring — Keychain on macOS,',
  'DPAPI on Windows, libsecret on Linux — and brokered by Studio, so an automation',
  'never holds a credential. Connect once in **Settings → Connections** and every',
  'automation on the machine can use it.',
  '',
  '**Nothing here is a Claritty account.** Where a service needs an OAuth app —',
  'Gmail, Jira, WhatsApp — you create your own. There is no Claritty client id to',
  'sign into, which is the point: your automations talk to your accounts.',
  '',
  `## The ${available.length} you can connect`,
  '',
  ...available.flatMap((r) => {
    const spec = localById.get(r.id);
    return [
      `### ${r.name}`,
      '',
      spec?.howToConnect ?? '',
      '',
      '| Field | | |',
      '| --- | --- | --- |',
      ...(spec?.fields ?? []).map(
        (f) => `| \`${f.key}\` | ${f.label} | ${f.secret ? 'secret' : 'not secret'}${f.placeholder ? ` · e.g. \`${f.placeholder}\`` : ''} |`,
      ),
      '',
      `Tools an automation can call: ${r.tools.map((t) => `\`${t}\``).join(', ')}`,
      '',
    ];
  }),
  '## Not available yet',
  '',
  'The platform provides these; Studio has no connector for them, so an automation',
  'calling one fails at run time. Adding one is a defined job — see the',
  '`add-an-integration` skill inside any automation.',
  '',
  missing.map((r) => `\`${r.id}\``).join(' · '),
  '',
].join('\n');

mkdirSync(join(ROOT, 'docs'), { recursive: true });
writeFileSync(join(ROOT, 'docs/connectors.md'), `${connectorDoc}\n`);

console.log(`catalog annotated — ${available.length} brokerable, ${missing.length} not`);
console.log(`available: ${available.map((r) => r.id).join(', ')}`);
